export const allProducts = [
  {
    id: 1,
    name: "Apple iphone 15",
    price: "$3999",
    imageUrl: "https://placehold.co/600x400/3498db/ffffff?text=iPhone+15",
    description: `DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities — so you don’t miss them while you’re doing something else.
INNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design.
48MP MAIN CAMERA — The 48MP Main camera shoots in super-high resolution.`,
    box: "Cell phone, USB-C Charge Cable",
    technicaldetails: "OS: iOS\nRAM: 6 GB\nStorage: 128GB",
    additionalinfo: "Manufacturer: Apple\nWarranty: 1 Year",
  },
  {
    id: 2,
    name: "Dell xps laptop",
    price: "$4599",
    imageUrl: "https://placehold.co/600x400/2ecc71/ffffff?text=Dell+XPS",
    description: "A powerful and sleek laptop for all your professional needs.",
    box: "Laptop, Power Adapter",
    technicaldetails: "OS: Windows 11\nRAM: 16 GB",
    additionalinfo: "Manufacturer: Dell\nWarranty: 1 Year",
  },
  {
    id: 3,
    name: "Hp Victus laptop",
    price: "$36500",
    imageUrl: "https://placehold.co/600x400/e74c3c/ffffff?text=HP+Victus",
    description: "A great budget gaming laptop.",
    box: "Laptop, Charger",
    technicaldetails: "OS: Windows 11\nRAM: 8 GB",
    additionalinfo: "Manufacturer: HP",
  },
  {
    id: 4,
    name: "Xiamomi 11s",
    price: "$1999",
    imageUrl: "https://placehold.co/600x400/f39c12/ffffff?text=Xiaomi+11s",
    description: "A fantastic mid-range smartphone.",
    box: "Phone, Charger",
    technicaldetails: "OS: Android 13\nRAM: 6 GB",
    additionalinfo: "Manufacturer: Xiaomi",
  },
  {
    id: 5,
    name: "Boat Earburds",
    price: "$199",
    imageUrl: "https://placehold.co/600x400/9b59b6/ffffff?text=Boat+Earbuds",
    description: "Wireless earbuds with great bass.",
    box: "Earbuds, Charging Case",
    technicaldetails: "Connectivity: Bluetooth 5.0\nBattery: 20 Hours",
    additionalinfo: "Manufacturer: Boat",
  },
  {
    id: 6,
    name: "Mi charger",
    price: "$49",
    imageUrl: "https://placehold.co/600x400/34495e/ffffff?text=Mi+Charger",
    description: "A fast and reliable charger.",
    box: "Charger",
    technicaldetails: "Output: 20W\nUSB-C",
    additionalinfo: "Manufacturer: Xiaomi",
  },
  {
    id: 7,
    name: "Boat Wired Headphones",
    price: "$49",
    imageUrl: "https://placehold.co/600x400/1abc9c/ffffff?text=Boat+Headphones",
    description: "Headphones with deep bass.",
    box: "Headphones",
    technicaldetails: "Connector: 3.5mm jack\nMic: Yes",
    additionalinfo: "Manufacturer: Boat",
  },
  {
    id: 8,
    name: "Kreo Mouse",
    price: "$499",
    imageUrl: "https://placehold.co/600x400/e67e22/ffffff?text=Kreo+Mouse",
    description: "A high-precision gaming mouse.",
    box: "Mouse, USB Dongle",
    technicaldetails: "DPI: 16000\nButtons: 6",
    additionalinfo: "Manufacturer: Kreo",
  },
  {
    id: 9,
    name: "Hp 4 series",
    price: "$2999",
    imageUrl: "https://placehold.co/600x400/d35400/ffffff?text=HP+4+Series",
    description: "A reliable laptop for work.",
    box: "Laptop, Charger",
    technicaldetails: "OS: Windows 11\nRAM: 8 GB",
    additionalinfo: "Manufacturer: HP",
  },
  {
    id: 10,
    name: "Asus Laptop",
    price: "$3999",
    imageUrl: "https://placehold.co/600x400/c0392b/ffffff?text=Asus+Laptop",
    description: "A powerful gaming laptop.",
    box: "Laptop, Charger",
    technicaldetails: "OS: Windows 11\nRAM: 16 GB",
    additionalinfo: "Manufacturer: Asus",
  },
  {
    id: 11,
    name: "Xiamomi Powerbank",
    price: "$199",
    imageUrl: "https://placehold.co/600x400/8e44ad/ffffff?text=Powerbank",
    description: "A 20000mAh powerbank.",
    box: "Powerbank, USB Cable",
    technicaldetails: "Capacity: 20000mAh\nPorts: 2",
    additionalinfo: "Manufacturer: Xiaomi",
  },
];